### ISSUE TITLE
access token模式下报错

### ISSUE THREAD

**Issue by richey07** [Chanzhaoyu/chatgpt-web#1075]
之前一直是可以的，今天总是报错undefined
[fetch failed]

POST https://bypass.duti.tech/api/conversation {
  body: {
    action: 'next',
    messages: [ [Object] ],
    model: 'gpt-4',
    parent_message_id: '5b91eab2-087f-455d-87f1-d42c9c303058'
  },
  headers: {
    Authorization: 'Bearer xxxxx',
    Accept: 'text/event-stream',
    'Content-Type': 'application/json'
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:46:15) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  }
}

**Comment by guohaomeng** [comment]
我也遇到了，一样的报错

```js
POST https://bypass.duti.tech/api/conversation {
  body: {
    action: 'next',
    messages: [ [Object] ],
    model: 'text-davinci-002-render-sha',
    parent_message_id: '778a8b26-8c39-4b43-b559-1aaba604003e'
  },
  headers: {
    Authorization: 'Bearer ey',
    Accept: 'text/event-stream',
    'Content-Type': 'application/json'
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:46:15) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  }
}
```

**Comment by yaoshu2006** [comment]
同问，这个https://bypass.duti.tech/api/conversation 是什么 ？

**Comment by justincnn** [comment]
早上还好好的，现在也碰到这个情况了，
是不是代理不稳定的原因

**Comment by ludashi2020** [comment]
代理挂掉了

**Comment by praiseqin** [comment]
切下反代就好了

**Comment by richey07** [comment]
> 切下反代就好了

哪个反代比较好？

**Comment by guohaomeng** [comment]
> > 切下反代就好了
> 
> 哪个反代比较好？

可以先换到社区代理,这个目前是能用的

```yml
      # 反向代理，可选
      API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
```

**Comment by richey07** [comment]
> > > 切下反代就好了
> > 
> > 
> > 哪个反代比较好？
> 
> 可以先换到社区代理,这个目前是能用的
> 
> ```yaml
>       # 反向代理，可选
>       API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
> ```

感谢！

**Comment by tristone13th** [comment]
> ```yaml
> https://api.pawan.krd/backend-api/conversation
> ```

这个反代也会欲言又止

**Comment by lqqkk** [comment]
+1
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.0.10/node_modules/chatgpt/build/index.js:46:15) {
  cause: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
      at TLSSocket.emit (node:events:513:28)
      at TLSSocket.emit (node:domain:489:12)
      at TLSSocket._finishInit (node:_tls_wrap:959:8)
      at ssl.onhandshakedone (node:_tls_wrap:743:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

**Comment by DevinLin01** [comment]
+1

**Comment by Steven-WZH** [comment]
> > > 切下反代就好了
> > 
> > 
> > 哪个反代比较好？
> 
> 可以先换到社区代理,这个目前是能用的
> 
> ```yaml
>       # 反向代理，可选
>       API_REVERSE_PROXY: https://api.pawan.krd/backend-api/conversation
> ```

这个反代代理的源站是啥，好像不是api.openai.com

**Comment by tanpengsccd** [comment]
这个反代可以自建吗?

**Comment by Steven-WZH** [comment]
> 这个反代可以自建吗?

应该可以，但是要ip没被openai屏蔽的服务器才可以反代

**Comment by tanpengsccd** [comment]
> > 这个反代可以自建吗?
> 
> 
> 
> 应该可以，但是要ip没被openai屏蔽的服务器才可以反代

大家用的哪个项目反代的啊？

**Comment by Steven-WZH** [comment]
> > > 这个反代可以自建吗?
> > 
> > 
> > 应该可以，但是要ip没被openai屏蔽的服务器才可以反代
> 
> 大家用的哪个项目反代的啊？

我直接用的宝塔的反代

**Comment by tanpengsccd** [comment]
bt 反代 出现cf盾你咋办呢？

**Comment by Steven-WZH** [comment]
所以我没成功，而且我服务器的ip端被openai封了，反代不了chat.openai.com，只能反代api.openai.com

**Comment by justincnn** [comment]
> > > > 这个反代可以自建吗?
> > > 
> > > 
> > > 应该可以，但是要ip没被openai屏蔽的服务器才可以反代
> > 
> > 大家用的哪个项目反代的啊？
> 
> 我直接用的宝塔的反代

请问宝塔的反代是哪个插件？

**Comment by Steven-WZH** [comment]
> > > > > 这个反代可以自建吗?
> > > > 
> > > > 
> > > > 应该可以，但是要ip没被openai屏蔽的服务器才可以反代
> > > 
> > > 大家用的哪个项目反代的啊？
> > 
> > 我直接用的宝塔的反代
> 
> 请问宝塔的反代是哪个插件？

新建一个网站，在网站设置里面添加反代就行了
