### ISSUE TITLE
pnpm start

### ISSUE THREAD

**Issue by dhicoc** [Chanzhaoyu/chatgpt-web#1111]
> chatgpt-web-service@1.0.0 start F:\Google下载\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service
> esno ./src/index.ts

f:\Google%E4%B8%8B%E8%BD%BD\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service\src\chatgpt\index.ts:30
  throw new Error('Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable')
        ^

Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable
    at options (f:\Google%E4%B8%8B%E8%BD%BD\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service\src\chatgpt\index.ts:30:9)
    at Object.<anonymous> (f:\Google%E4%B8%8B%E8%BD%BD\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service\src\chatgpt\index.ts:181:10)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.F (F:\Google下载\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at <anonymous> (f:\Google%E4%B8%8B%E8%BD%BD\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service\src\index.ts:4:60)
    at Object.<anonymous> (f:\Google%E4%B8%8B%E8%BD%BD\chatgpt-web-2.10.8\chatgpt-web-2.10.8\service\src\index.ts:86:80)

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Song-Mao** [comment]
确少OPENAI_API_KEY or OPENAI_ACCESS_TOKEN 环境变量，仔细看文档，新建一个.env文件配置一下你的key
