### ISSUE TITLE
用Access Token 部署出现gpt返回信息不完整的情况

### ISSUE THREAD

**Issue by fishslidenas** [Chanzhaoyu/chatgpt-web#1170]
应用是部署在Railway上的，两个代理我都试了，都是同样的问题。
之前我记得出现过只返回一个字的情况，但是修复了。这次升级到2.10.9之后，又出现了这种情况。但是返回的字数比之前多，具体就类似如下截图：
![gpt_error](https://user-images.githubusercontent.com/84767102/229433513-1942de4f-bce0-4c33-9e6d-42adbc117b53.png)

**Comment by fishslidenas** [comment]
回溯到2.10.8版本就没有这个问题了。

**Comment by newreport** [comment]
我也是这个错误

**Comment by newreport** [comment]
docker日志
`
SyntaxError: Unexpected number in JSON at position 4
    at JSON.parse (<anonymous>)
    at onMessage (file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:622:47)
    at file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:62:7
    at parseEventStreamLine (file:///app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/dist/index.js:73:9)
    at Object.feed (file:///app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/dist/index.js:61:7)
    at feed (file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:84:12)
    at fetchSSE (file:///app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:100:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by iknow2333** [comment]
不全加一，gpt4写个三行就自动截断，看官网的聊天记录好好的

**Comment by xiaosaaaa** [comment]
看来是有bug？

**Comment by HelloMorningStar** [comment]
gpt-3.5-turbo/gpt-3.5-turbo-0301，用API-key同样2.10.9版本不能完整返回信息，退回到2.10.6正常。2.10.7/2.10.8还未用过。

**Comment by yingw** [comment]
我这里用release的2.10.9也是，后台报错：

**Comment by yxrind** [comment]
我是在docker上部署的，用Access Token也出现了这个问题，还特意修改文件重新打包，并没有解决，但是我使用api是正常的
