### ISSUE TITLE
对话出现memory access out of bounds

### ISSUE THREAD

**Issue by hyyxiaoluo** [Chanzhaoyu/chatgpt-web#1311]
安装部署我是把service/.env.example修改成service/.env文件，然后添加的key，
之后运行的
docker build -t chatgpt-web .
下面这条命令我运行后一直是卡在3002 is running的地方也不能输入命令
# 前台运行
docker run --name chatgpt-web --rm -it -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key chatgpt-web
然后我就放弃了上面的又运行
# 后台运行
docker run --name chatgpt-web -d -p 127.0.0.1:3002:3002 --env OPENAI_API_KEY=your_api_key chatgpt-web
这一步也是坑我了，这玩意运行后我这边又访问不了，最后把127.0.0.1删了才可以，我丢无语死，我这小白太难了，也不晓得还有问题没，现在能访问了，但是进去页面对话又出现错误
![image](https://user-images.githubusercontent.com/102205671/230667260-035022ad-4194-4e55-9374-0bdac93861e2.png)
天杀啊，炸了
我使用 Railway 部署是能访问的，这是为啥啊，有大佬教教不，回复帮帮孩子好不好

**Comment by Chanzhaoyu** [comment]
你直接拉取镜像试试？

**Comment by hyyxiaoluo** [comment]
> 你直接拉取镜像试试？
哇，大佬，谢谢回复，但是我不是很明白你的意思，我服务器运行的git clone https://github.com/Chanzhaoyu/chatgpt-web.git拉取的源码，你说的镜像是docker拉取还是啥呢，我docker的compose运行失败的，架构不支持，能不能给下具体的命令啥的我去研究着执行下，还是说是变量添加哪里有问题？我Railway 部署直接用的你的模板添加的api-key变量直接能用，自己服务器部署的把
service/.env.example修改成service/.env文件，然后添加的key反而是不能用，我按照的教程是这个，大佬你看看是不是有问题
https://juejin.cn/post/7212799872961380413

**Comment by necopp** [comment]
小白建议用docker-compose，看我写的教程，有

**Comment by hyyxiaoluo** [comment]
> 小白建议用docker-compose，看我写的教程，有

我的服务器不被支持compose，我compose运行是失败的

**Comment by necopp** [comment]
那就装一个-实在不行，可以找我帮你装q2630622552

**Comment by fu7100** [comment]
我也遇到同样的问题，我的vps是s390架构不是x86的，不能直接使用dockerhub上的镜像，我自己构建后运行对话就RuntimeError: memory access out of bounds

**Comment by fu7100** [comment]
![图片](https://user-images.githubusercontent.com/59348973/230729526-9e12a120-b829-4368-b3f3-31ea4093f6e4.png)

**Comment by hyyxiaoluo** [comment]
> 我也遇到同样的问题，我的vps是s390架构不是x86的，不能直接使用dockerhub上的镜像，我自己构建后运行对话就RuntimeError: memory access out of bounds
> 
> RuntimeError: memory access out of bounds at wasm://wasm/00b63e2e:wasm-function[661]:0x6d175 at wasm://wasm/00b63e2e:wasm-function[154]:0x48aac at Tiktoken.encode (/app/node_modules/.pnpm/@dqbd+tiktoken@1.0.2/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:257:18) at encode (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:11:20) at ChatGPTAPI._getTokenCount (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:405:12) at ChatGPTAPI._buildMessages (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:369:48) at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:199:59) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async chatReplyProcess (file:///app/build/index.mjs:104:22) at async file:///app/build/index.mjs:241:5
你的下面的报错是日志里面的么，方便加个联系方式讨论下不

**Comment by fu7100** [comment]
@hyyxiaoluo 作者你好，docker日志如下，问题可以发邮件fu7100@gmail.com讨论
root@ubuntu:~# docker logs chatgpt-web

> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

Server is running on port 3002
RuntimeError: memory access out of bounds
    at wasm://wasm/00b63e2e:wasm-function[661]:0x6d175
    at wasm://wasm/00b63e2e:wasm-function[154]:0x48aac
    at Tiktoken.encode (/app/node_modules/.pnpm/@dqbd+tiktoken@1.0.2/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:257:18)
    at encode (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:11:20)
    at ChatGPTAPI._getTokenCount (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:405:12)
    at ChatGPTAPI._buildMessages (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:369:48)
    at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/index.mjs:104:22)
    at async file:///app/build/index.mjs:241:5
RuntimeError: memory access out of bounds
    at wasm://wasm/00b63e2e:wasm-function[661]:0x6d175
    at wasm://wasm/00b63e2e:wasm-function[154]:0x48aac
    at Tiktoken.encode (/app/node_modules/.pnpm/@dqbd+tiktoken@1.0.2/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:257:18)
    at encode (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:11:20)
    at ChatGPTAPI._getTokenCount (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:405:12)
    at ChatGPTAPI._buildMessages (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:369:48)
    at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/index.mjs:104:22)
    at async file:///app/build/index.mjs:241:5
RuntimeError: memory access out of bounds
    at wasm://wasm/00b63e2e:wasm-function[661]:0x6d175
    at wasm://wasm/00b63e2e:wasm-function[154]:0x48aac
    at Tiktoken.encode (/app/node_modules/.pnpm/@dqbd+tiktoken@1.0.2/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:257:18)
    at encode (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:11:20)
    at ChatGPTAPI._getTokenCount (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:405:12)
    at ChatGPTAPI._buildMessages (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:369:48)
    at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/index.mjs:104:22)
    at async file:///app/build/index.mjs:241:5
RuntimeError: memory access out of bounds
    at wasm://wasm/00b63e2e:wasm-function[661]:0x6d175
    at wasm://wasm/00b63e2e:wasm-function[154]:0x48aac
    at Tiktoken.encode (/app/node_modules/.pnpm/@dqbd+tiktoken@1.0.2/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:257:18)
    at encode (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:11:20)
    at ChatGPTAPI._getTokenCount (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:405:12)
    at ChatGPTAPI._buildMessages (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:369:48)
    at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/index.mjs:104:22)
    at async file:///app/build/index.mjs:241:5
root@ubuntu:~#
