### ISSUE TITLE
OpenAI timed out waiting for response

### ISSUE THREAD

**Issue by luobo007** [Chanzhaoyu/chatgpt-web#1400]
调用直接报超时了，换apikey也不行。是什么原因呢

2023-04-12 16:46:53 TimeoutError: OpenAI timed out waiting for response
2023-04-12 16:46:53     at file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24
2023-04-12 16:46:53     at new Promise (<anonymous>)
2023-04-12 16:46:53     at pTimeout (file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
2023-04-12 16:46:53     at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
2023-04-12 16:46:53     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-12 16:46:53     at async chatReplyProcess (file:///app/build/index.mjs:100:22)
2023-04-12 16:46:53     at async file:///app/build/index.mjs:237:5

**Comment by luobo007** [comment]
更改TIMEOUT_MS为0 也不行

**Comment by Chanzhaoyu** [comment]
这是网络连接不顺

**Comment by yiqiquhuxi** [comment]
hava a solution?
