### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by sunfg** [Chanzhaoyu/chatgpt-web#1540]
docker 启动的

TimeoutError: OpenAI timed out waiting for response
    at file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24
    at new Promise (<anonymous>)
    at pTimeout (file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/index.mjs:100:22)
    at async file:///app/build/index.mjs:237:5

**Comment by huangwb8** [comment]
会使用docker的话，可以看看我之前的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
