### ISSUE TITLE
填写了 OPENAI_API_KEY，获取不到

### ISSUE THREAD

**Issue by waylandGss** [Chanzhaoyu/chatgpt-web#1550]
mac@xiaoxiaohaodeiMac service % pnpm start

> chatgpt-web-service@1.0.0 start /Users/mac/Desktop/chatgpt-web/service
> esno ./src/index.ts

/Users/mac/Desktop/chatgpt-web/service/src/chatgpt/index.ts:33
  throw new Error('Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable')
        ^

Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable
    at options (/Users/mac/Desktop/chatgpt-web/service/src/chatgpt/index.ts:33:9)
    at Object.<anonymous> (/Users/mac/Desktop/chatgpt-web/service/src/chatgpt/index.ts:212:10)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.F (/Users/mac/Desktop/chatgpt-web/service/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at <anonymous> (/Users/mac/Desktop/chatgpt-web/service/src/index.ts:4:60)
    at Object.<anonymous> (/Users/mac/Desktop/chatgpt-web/service/src/index.ts:89:80)

Node.js v18.13.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by waylandGss** [comment]
已经解决了，
