### ISSUE TITLE
使用web api的方式提示报这个错误，怎么解决？

### ISSUE THREAD

**Issue by Tom722** [Chanzhaoyu/chatgpt-web#1552]
Error: ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined
at ChatGPTUnofficialProxyAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:487:13)
at chatReplyProcess (file:///app/build/index.mjs:100:32)
at file:///app/build/index.mjs:237:11
at Layer.handle [as handle_request] (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
at next (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
at file:///app/node_modules/.pnpm/express-rate-limit@6.7.0_express@4.18.2/node_modules/express-rate-limit/dist/index.mjs:216:7
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///app/node_modules/.pnpm/express-rate-limit@6.7.0_express@4.18.2/node_modules/express-rate-limit/dist/index.mjs:124:5

**Comment by huangwb8** [comment]
@Tom722 

对于这类报错， `conversationId and parentMessageId must both be set or both be undefined at ChatGPTUnofficialProxyAPI.sendMessage` ，你可以试试删除旧对话，然后用新对话试试。 如果还是不行，就看看其它小伙伴有什么意见吧

如果会docker，可以用docker自建，比如稳定些
