### ISSUE TITLE
Debian GNU/Linux 10  启动正常，用网络上的地址一访问就报错The service is no longer running

### ISSUE THREAD

**Issue by HaloLyyL** [Chanzhaoyu/chatgpt-web#1692]
The service is no longer running
/home/chatgpt-web/node_modules/esbuild/lib/main.js:1100
                    reject(new Error(error2));
                           ^

Error: The service was stopped
    at /home/chatgpt-web/node_modules/esbuild/lib/main.js:1100:28
    at responseCallbacks.<computed> (/home/chatgpt-web/node_modules/esbuild/lib/main.js:697:9)
    at Socket.afterClose (/home/chatgpt-web/node_modules/esbuild/lib/main.js:687:28)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by HaloLyyL** [comment]
![image](https://github.com/Chanzhaoyu/chatgpt-web/assets/66347537/7842482c-59d5-433a-a0d4-35d791f898ea)

**Comment by CrazyAndy** [comment]
我也遇到同样的问题，请问该如何解决呢，是因为chatgpt禁止访问的原因吗？
