### ISSUE TITLE
Error on loading website (with start command npm run build-only)

### ISSUE THREAD

**Issue by huanhoahongso3-collab** [Chanzhaoyu/chatgpt-web#1916]
plugin:vite:vue] The service is no longer running
/home/runner/ChatGPT-Web/src/views/exception/500/index.vue
    at /home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:816:29
    at sendRequest (/home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:693:14)
    at start (/home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:814:9)
    at Object.transform2 [as transform] (/home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:879:5)
    at /home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:2180:77
    at new Promise (<anonymous>)
    at Object.transform (/home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:2180:36)
    at transform (/home/runner/ChatGPT-Web/node_modules/.pnpm/esbuild@0.17.11/node_modules/esbuild/lib/main.js:2013:62)
    at Module.transformWithEsbuild (file:///home/runner/ChatGPT-Web/node_modules/.pnpm/vite@4.2.0_@types+node@18.14.6_less@4.1.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:13500:30)
    at async transformMain (/home/runner/ChatGPT-Web/node_modules/.pnpm/@vitejs+plugin-vue@4.0.0_vite@4.2.0_vue@3.2.47/node_modules/@vitejs/plugin-vue/dist/index.cjs:2342:34
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

**Comment by huanhoahongso3-collab** [comment]
More: deployed on replit
