### ISSUE TITLE
将项目打包为docker镜像出现错误

### ISSUE THREAD

**Issue by emmmua** [Chanzhaoyu/chatgpt-web#2009]
将项目打包为docker镜像出错大家有没有遇到过这种问题
修改了很多个版本，node v16-v20都试过了，不行，求大佬帮帮忙，帮我打包成dockr镜像

## 版本
```sh
root@ubuntu:/docker/chat/chatgpt-web-2.11.1# node -v
v18.17.1
root@ubuntu:/docker/chat/chatgpt-web-2.11.1# pnpm -v
8.12.1
root@ubuntu:/docker/chat/chatgpt-web-2.11.1# npm -v
10.2.5
root@ubuntu:/docker/chat/chatgpt-web-2.11.1# 
```

## 完整日志
```log
root@ubuntu:/docker/chat/chatgpt-web-2.11.1# docker build -t chatgpt-web .
[+] Building 142.7s (14/21)                                                                                                                                                               docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                0.1s
 => => transferring dockerfile: 833B                                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                                   0.0s
 => => transferring context: 109B                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                                                                  2.8s
 => [frontend 1/8] FROM docker.io/library/node:lts-alpine@sha256:9e38d3d4117da74a643f67041c83914480b335c3bd44d37ccf5b5ad86cd715d1                                                                   0.0s
 => [internal] load build context                                                                                                                                                                   0.0s
 => => transferring context: 779.32kB                                                                                                                                                               0.0s
 => CACHED [frontend 2/8] RUN npm install pnpm -g                                                                                                                                                   0.0s
 => CACHED [frontend 3/8] WORKDIR /app                                                                                                                                                              0.0s
 => CACHED [stage-2 4/9] COPY /service/package.json /app                                                                                                                                            0.0s
 => CACHED [stage-2 5/9] COPY /service/pnpm-lock.yaml /app                                                                                                                                          0.0s
 => CACHED [frontend 4/8] COPY ./package.json /app                                                                                                                                                  0.0s
 => CACHED [frontend 5/8] COPY ./pnpm-lock.yaml /app                                                                                                                                                0.0s
 => ERROR [stage-2 6/9] RUN pnpm install --production && rm -rf /root/.npm /root/.pnpm-store /usr/local/share/.cache /tmp/*                                                                       139.6s
 => ERROR [backend 6/8] RUN pnpm install                                                                                                                                                          139.6s
 => CANCELED [frontend 6/8] RUN pnpm install                                                                                                                                                      139.7s
------                                                                                                                                                                                                   
 > [stage-2 6/9] RUN pnpm install --production && rm -rf /root/.npm /root/.pnpm-store /usr/local/share/.cache /tmp/*:                                                                                    
2.856  WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.10.0","pnpm":"8.12.1"})                                                                                     
5.429 Progress: resolved 0, reused 0, downloaded 1, added 0                                                                                                                                              
6.435 Progress: resolved 1, reused 0, downloaded 1, added 0                                                                                                                                              
21.63  WARN  GET https://registry.npmjs.org/chatgpt/-/chatgpt-5.1.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.                                                                    
21.63  WARN  GET https://registry.npmjs.org/dotenv/-/dotenv-16.0.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.                                                                     
21.64  WARN  GET https://registry.npmjs.org/express/-/express-4.18.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.                                                                   
21.64  WARN  GET https://registry.npmjs.org/express-rate-limit/-/express-rate-limit-6.7.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.64  WARN  GET https://registry.npmjs.org/rimraf/-/rimraf-4.3.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.67  WARN  GET https://registry.npmjs.org/@types/express/-/express-4.17.17.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.67  WARN  GET https://registry.npmjs.org/tsup/-/tsup-6.6.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.68  WARN  GET https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-7.0.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.72  WARN  GET https://registry.npmjs.org/@antfu/eslint-config/-/eslint-config-0.35.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.74  WARN  GET https://registry.npmjs.org/@types/node/-/node-18.14.6.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
27.10  WARN  GET https://registry.npmjs.org/axios/-/axios-1.3.4.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
27.13  WARN  GET https://registry.npmjs.org/eslint/-/eslint-8.35.0.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
55.51  WARN  GET https://registry.npmjs.org/chatgpt/-/chatgpt-5.1.2.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.52  WARN  GET https://registry.npmjs.org/dotenv/-/dotenv-16.0.3.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.53  WARN  GET https://registry.npmjs.org/rimraf/-/rimraf-4.3.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.53  WARN  GET https://registry.npmjs.org/express/-/express-4.18.2.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.53  WARN  GET https://registry.npmjs.org/express-rate-limit/-/express-rate-limit-6.7.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.56  WARN  GET https://registry.npmjs.org/@types/express/-/express-4.17.17.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.59  WARN  GET https://registry.npmjs.org/tsup/-/tsup-6.6.3.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.59  WARN  GET https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-7.0.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.59  WARN  GET https://registry.npmjs.org/@antfu/eslint-config/-/eslint-config-0.35.3.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.62  WARN  GET https://registry.npmjs.org/@types/node/-/node-18.14.6.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
61.01  WARN  GET https://registry.npmjs.org/axios/-/axios-1.3.4.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
61.01  WARN  GET https://registry.npmjs.org/eslint/-/eslint-8.35.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
126.4  WARN  GET https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.1.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
127.4  WARN  GET https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.0.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
127.4  WARN  GET https://registry.npmjs.org/esno/-/esno-0.16.3.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
139.5  ETIMEDOUT  request to https://registry.npmjs.org/@antfu/eslint-config/-/eslint-config-0.35.3.tgz failed, reason: 
139.5 
139.5 This error happened while installing a direct dependency of /app
139.5 
139.5 FetchError: request to https://registry.npmjs.org/@antfu/eslint-config/-/eslint-config-0.35.3.tgz failed, reason: 
139.5     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:73746:18)
139.5     at ClientRequest.emit (node:events:514:28)
139.5     at TLSSocket.socketErrorListener (node:_http_client:495:9)
139.5     at TLSSocket.emit (node:events:526:35)
139.5     at emitErrorNT (node:internal/streams/destroy:151:8)
139.5     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
139.5     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
------
------
 > [backend 6/8] RUN pnpm install:
2.860  WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.10.0","pnpm":"8.12.1"})
21.67  WARN  GET https://registry.npmjs.org/eslint/-/eslint-8.35.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.67  WARN  GET https://registry.npmjs.org/rimraf/-/rimraf-4.3.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.68  WARN  GET https://registry.npmjs.org/chatgpt/-/chatgpt-5.1.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.68  WARN  GET https://registry.npmjs.org/dotenv/-/dotenv-16.0.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.69  WARN  GET https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-3.0.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.70  WARN  GET https://registry.npmjs.org/tsup/-/tsup-6.6.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.72  WARN  GET https://registry.npmjs.org/@types/node/-/node-18.14.6.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.72  WARN  GET https://registry.npmjs.org/express/-/express-4.18.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.74  WARN  GET https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.1.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.74  WARN  GET https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
21.74  WARN  GET https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
27.18  WARN  GET https://registry.npmjs.org/@types/express/-/express-4.17.17.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
55.56  WARN  GET https://registry.npmjs.org/rimraf/-/rimraf-4.3.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.57  WARN  GET https://registry.npmjs.org/eslint/-/eslint-8.35.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.59  WARN  GET https://registry.npmjs.org/dotenv/-/dotenv-16.0.3.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.59  WARN  GET https://registry.npmjs.org/chatgpt/-/chatgpt-5.1.2.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.59  WARN  GET https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-3.0.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.62  WARN  GET https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.62  WARN  GET https://registry.npmjs.org/@types/node/-/node-18.14.6.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.62  WARN  GET https://registry.npmjs.org/express/-/express-4.18.2.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.63  WARN  GET https://registry.npmjs.org/tsup/-/tsup-6.6.3.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.63  WARN  GET https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.1.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
55.65  WARN  GET https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.0.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
61.08  WARN  GET https://registry.npmjs.org/@types/express/-/express-4.17.17.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
126.5  WARN  GET https://registry.npmjs.org/axios/-/axios-1.3.4.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
126.5  WARN  GET https://registry.npmjs.org/express-rate-limit/-/express-rate-limit-6.7.0.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
127.4  WARN  GET https://registry.npmjs.org/@antfu/eslint-config/-/eslint-config-0.35.3.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
127.5  WARN  GET https://registry.npmjs.org/esno/-/esno-0.16.3.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
139.5  ETIMEDOUT  request to https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-3.0.0.tgz failed, reason: 
139.5 
139.5 This error happened while installing a direct dependency of /app
139.5 
139.5 FetchError: request to https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-3.0.0.tgz failed, reason: 
139.5     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:73746:18)
139.5     at ClientRequest.emit (node:events:514:28)
139.5     at TLSSocket.socketErrorListener (node:_http_client:495:9)
139.5     at TLSSocket.emit (node:events:526:35)
139.5     at emitErrorNT (node:internal/streams/destroy:151:8)
139.5     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
139.5     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
------
Dockerfile:29
--------------------
  27 |     COPY /service/pnpm-lock.yaml /app
  28 |     
  29 | >>> RUN pnpm install
  30 |     
  31 |     COPY /service /app
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm install" did not complete successfully: exit code: 1
```

**Comment by emmmua** [comment]
大佬们能不能直接帮我打包一下，我就修改了一些东西，头像信息等等，版权信息保留着。
链接：https://pan.baidu.com/s/1wMlgwSDSqI-2ssUmfIamLw?pwd=1234 
提取码：1234
