### ISSUE TITLE
求助！！[request to https://chat.duti.tech/api/conversation failed, reason: Client network socket disconnected before secure TLS connection was established]

### ISSUE THREAD

**Issue by MySheep** [Chanzhaoyu/chatgpt-web#496]
之前用的好好的，代理也是正常的。现在是这个错误：
c:\APP\ChatGPT\service\node_modules\.pnpm\node-fetch@3.3.0\node_modules\node-fetch\src\index.js:108
                        reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
                               ^

FetchError: request to https://chat.duti.tech/api/conversation failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (c:\APP\ChatGPT\service\node_modules\.pnpm\node-fetch@3.3.0\node_modules\node-fetch\src\index.js:108:11)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}

**Comment by Chanzhaoyu** [comment]
添加这个

```
API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
```

**Comment by heylary** [comment]
> 



> 添加这个
> 
> ```
> API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
> ```

Server is running on port 3002
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchSSE (d:\chatgpt-web-main\service\node_modules\.pnpm\chatgpt@5.0.9\node_modules\chatgpt\build\index.js:46:15) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
请问这个是什么错误

**Comment by Peins** [comment]
我也是这个错误：
Server is running on port 3002
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchSSE (/var/www/chatgpt-web/service/node_modules/.pnpm/chatgpt@5.0.9/node_modules/chatgpt/build/index.js:46:15) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8369:13)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

**Comment by MySheep** [comment]
> > 
> 
> > 添加这个
> > ```
> > API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
> > ```
> 
> Server is running on port 3002 TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11413:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at fetchSSE (d:\chatgpt-web-main\service\node_modules.pnpm\chatgpt@5.0.9\node_modules\chatgpt\build\index.js:46:15) { cause: ConnectTimeoutError: Connect Timeout Error at onConnectTimeout (node:internal/deps/undici/undici:8380:28) at node:internal/deps/undici/undici:8338:50 at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37) at process.processImmediate (node:internal/timers:476:21) { code: 'UND_ERR_CONNECT_TIMEOUT' } } 请问这个是什么错误



> 添加这个
> 
> ```
> API_REVERSE_PROXY=https://gpt.pawan.krd/backend-api/conversation
> ```

好的，谢谢！解决了
