### ISSUE TITLE
运行服务报错

### ISSUE THREAD

**Issue by ahjdzx** [Chanzhaoyu/chatgpt-web#7]
```
23:57:47 ❯ pnpm run service

> chatgpt-web@1.0.4 service /Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web
> esno ./service/index.ts

/Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web/node_modules/.pnpm/chatgpt@4.2.0/node_modules/chatgpt/build/index.js:15
  throw new Error("Invalid environment: global fetch not defined");
        ^

Error: Invalid environment: global fetch not defined
    at <anonymous> (/Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web/node_modules/.pnpm/chatgpt@4.2.0/node_modules/chatgpt/build/index.js:15:9)
    at Object.<anonymous> (/Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web/node_modules/.pnpm/chatgpt@4.2.0/node_modules/chatgpt/build/index.js:76:18)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.F (/Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at <anonymous> (/Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web/service/chatgpt.ts:2:28)
    at Object.<anonymous> (/Users/zhangxin/work/src/github.com/Chanzhaoyu/chatgpt-web/service/chatgpt.ts:48:16)
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by Chanzhaoyu** [comment]
需要 node 版本为 14 或者 18 以上，推荐 18
