### ISSUE TITLE
 Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

### ISSUE THREAD

**Issue by zhuyuntian** [Chanzhaoyu/chatgpt-web#784]
Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable
    at __defProp (c:\works\product\chatgpt\chatgpt-web\service\build\index.js:70:9)
    at Object.<anonymous> (c:\works\product\chatgpt\chatgpt-web\service\build\index.js:262:80)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.F (C:\works\product\chatgpt\chatgpt-web\service\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)

**Comment by Chanzhaoyu** [comment]
自己创建一个 `.env` 文件，将 `.env.example` 的内容复制进去
