### ISSUE TITLE
[[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error]

### ISSUE THREAD

**Issue by nikissXI** [Chanzhaoyu/chatgpt-web#900]
请问这个问题怎么解决
![image](https://user-images.githubusercontent.com/31379266/227772937-0bfbea22-78da-41ff-9a1b-1a959d9e6e16.png)

**Comment by hncboy** [comment]
多试几次

**Comment by nikissXI** [comment]
> 多试几次

从哪方面重试，比较懵逼

**Comment by hncboy** [comment]
> > 多试几次
> 
> 从哪方面重试，比较懵逼

多发送几次消息，偶尔网络问题。

**Comment by nikissXI** [comment]
> > > 多试几次
> > 
> > 
> > 从哪方面重试，比较懵逼
> 
> 多发送几次消息，偶尔网络问题。

是我梯子问题还是chatgpt的服务器问题？

**Comment by luckywangxi** [comment]
sendMessage (66 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-26'
    },
    { role: 'user', content: '你是谁 用多国语言介绍你自己', name: undefined }
  ],
  stream: true
}
TimeoutError: OpenAI timed out waiting for response
    at <anonymous> (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24)
    at new Promise (<anonymous>)
    at pTimeout (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at Object.sendMessage (/app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at chatReplyProcess (/app/build/index.js:9813:22)
    at <anonymous> (/app/build/index.js:10179:20)
我的是还没发完就G了 timed out

**Comment by nikissXI** [comment]
突然又好了

**Comment by sdlkhfksl** [comment]
[OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error

**Comment by nikissXI** [comment]
> [OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error

检查代理

**Comment by zsinba** [comment]
使用Azure Openai，偶发，概率挺大。
