### ISSUE TITLE
TimeoutError: OpenAI timed out waiting for response

### ISSUE THREAD

**Issue by luckywangxi** [Chanzhaoyu/chatgpt-web#904]
TimeoutError: OpenAI timed out waiting for response
    at <anonymous> (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24)
    at new Promise (<anonymous>)
    at pTimeout (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at Object.sendMessage (/app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at chatReplyProcess (/app/build/index.js:9813:22)
    at <anonymous> (/app/build/index.js:10179:20)
sendMessage (66 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-26'
    },
    { role: 'user', content: '你是谁 用多国语言介绍你自己', name: undefined }
  ],
  stream: true
}
TimeoutError: OpenAI timed out waiting for response
    at <anonymous> (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24)
    at new Promise (<anonymous>)
    at pTimeout (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at Object.sendMessage (/app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at chatReplyProcess (/app/build/index.js:9813:22)
    at <anonymous> (/app/build/index.js:10179:20)
![image](https://user-images.githubusercontent.com/112324550/227777308-d3858f22-3636-46c8-9833-aaa08fc675e0.png)
输出没有完成就timed out

**Comment by luckywangxi** [comment]
已解决，更改TIMEOUT_MS为0

**Comment by williamzhang11** [comment]
想问下，你是通过docker部署的吗

**Comment by luckywangxi** [comment]
> 想问下，你是通过docker部署的吗

是的，已解决，更改docker compose 的TIMEOUT_MS为0

**Comment by luobo007** [comment]
更改TIMEOUT_MS为0 也不行

**Comment by arthur19q3** [comment]
更改TIMEOUT_MS为0 也不行
