### ISSUE TITLE
让GPT写代码的时候，不会携带上下文进行请求

### ISSUE THREAD

**Issue by guiguichuan** [Chanzhaoyu/chatgpt-web#978]
![image](https://user-images.githubusercontent.com/90624317/228242427-c3b4e9bd-b8e9-4a48-b2d1-e49947acdce0.png)

**Comment by Rayzggz** [comment]
+1 
同报错
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by crosys** [comment]
同样的问题，有解决方案吗？

**Comment by Bisstocuz** [comment]
我也碰到了这个bug

**Comment by starmoon-1134** [comment]
我也遇到过，不过下边请求却是正常的
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/16525284/228464453-60dd3c8a-ce02-4119-ac55-ee5ec4037151.png">

对话连不上估计和上个问题的回答超时有关，在service/service.log能看到这样的日志
```
/root/chatgpt-web/service/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70
                const timeoutError = new TimeoutError();
                                     ^

TimeoutError: OpenAI timed out waiting for response
    at <anonymous> (/root/chatgpt-web/service/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24)
    at new Promise (<anonymous>)
    at pTimeout (/root/chatgpt-web/service/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at Object.sendMessage (/root/chatgpt-web/service/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at chatReplyProcess (/root/chatgpt-web/service/src/chatgpt/index.ts:107:22)
    at <anonymous> (/root/chatgpt-web/service/src/index.ts:28:5)
```

**Comment by starmoon-1134** [comment]
估计和这个是同一个问题

**Comment by hqzhon** [comment]
提交了一个merge request，不过没有审批，可以参照这个修改携带上下文
https://github.com/Chanzhaoyu/chatgpt-web/pull/985/files

**Comment by guiguichuan** [comment]
![image](https://user-images.githubusercontent.com/90624317/228527115-0459ad7b-f980-4260-ad51-431c89c9a344.png)
我的报错是这样的， 和 https://github.com/Chanzhaoyu/chatgpt-web/issues/904 是同一个问题
所以我的解决方案就是 将TIMEOUT_MS设置为0。现在可以了

**Comment by guiguichuan** [comment]
> 同样的问题，有解决方案吗？
> 
> 补充：似乎代码没输出完的时候，用“还有吗？”代替“继续”是可以的，大家试试看。
和 https://github.com/Chanzhaoyu/chatgpt-web/issues/904 是同一个问题，将TIMEOUT_MS设置为0。现在可以了

**Comment by mcqnby** [comment]
> ![image](https://user-images.githubusercontent.com/90624317/228527115-0459ad7b-f980-4260-ad51-431c89c9a344.png) 我的报错是这样的， 和 #904 是同一个问题 所以我的解决方案就是 将TIMEOUT_MS设置为0。现在可以了

按这个方法解决了不携带上下文请求的问题！

**Comment by cvpv** [comment]
我也遇到这个问题，请问是否解决
？
